
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Administrador_de_entradas_para_la_Superliga.GlobalSvc
{

using System;
    using System.Collections.Generic;
    
public partial class Billet
{

    public int @int { get; set; }

    public string numSocio { get; set; }

    public int idPlace { get; set; }

    public int idMatch { get; set; }



    public virtual Match Match { get; set; }

    public virtual Places Places { get; set; }

    public virtual Socios Socios { get; set; }

}

}
