//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("Model", "FK__Billet__idMatch__267ABA7A", "Match", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Match), "Billet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Billet), true)]
[assembly: EdmRelationshipAttribute("Model", "FK__Billet__idPlace__22AA2996", "Places", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Places), "Billet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Billet), true)]
[assembly: EdmRelationshipAttribute("Model", "FK__Billet__numSocio__1BFD2C07", "Socios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Socios), "Billet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Billet), true)]
[assembly: EdmRelationshipAttribute("Model", "FK__Places__idTribun__21B6055D", "Tribunes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Tribunes), "Places", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Places), true)]
[assembly: EdmRelationshipAttribute("Model", "FK__Table__idTribune__1ED998B2", "Tribunes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Tribunes), "Table", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Administrador_de_entradas_para_la_Superliga.GlobalSvc.Table), true)]

#endregion

namespace Administrador_de_entradas_para_la_Superliga.GlobalSvc
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class Entities1 : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet Entities1 à l'aide de la chaîne de connexion trouvée dans la section 'Entities1' du fichier de configuration d'application.
        /// </summary>
        public Entities1() : base("name=Entities1", "Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Entities1.
        /// </summary>
        public Entities1(string connectionString) : base(connectionString, "Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Entities1.
        /// </summary>
        public Entities1(EntityConnection connection) : base(connection, "Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Match> Match
        {
            get
            {
                if ((_Match == null))
                {
                    _Match = base.CreateObjectSet<Match>("Match");
                }
                return _Match;
            }
        }
        private ObjectSet<Match> _Match;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Billet> Billet
        {
            get
            {
                if ((_Billet == null))
                {
                    _Billet = base.CreateObjectSet<Billet>("Billet");
                }
                return _Billet;
            }
        }
        private ObjectSet<Billet> _Billet;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Places> Places
        {
            get
            {
                if ((_Places == null))
                {
                    _Places = base.CreateObjectSet<Places>("Places");
                }
                return _Places;
            }
        }
        private ObjectSet<Places> _Places;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Socios> Socios
        {
            get
            {
                if ((_Socios == null))
                {
                    _Socios = base.CreateObjectSet<Socios>("Socios");
                }
                return _Socios;
            }
        }
        private ObjectSet<Socios> _Socios;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Table> Table
        {
            get
            {
                if ((_Table == null))
                {
                    _Table = base.CreateObjectSet<Table>("Table");
                }
                return _Table;
            }
        }
        private ObjectSet<Table> _Table;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Tribunes> Tribunes
        {
            get
            {
                if ((_Tribunes == null))
                {
                    _Tribunes = base.CreateObjectSet<Tribunes>("Tribunes");
                }
                return _Tribunes;
            }
        }
        private ObjectSet<Tribunes> _Tribunes;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Match. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMatch(Match match)
        {
            base.AddObject("Match", match);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Billet. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToBillet(Billet billet)
        {
            base.AddObject("Billet", billet);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Places. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPlaces(Places places)
        {
            base.AddObject("Places", places);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Socios. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSocios(Socios socios)
        {
            base.AddObject("Socios", socios);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Table. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTable(Table table)
        {
            base.AddObject("Table", table);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Tribunes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTribunes(Tribunes tribunes)
        {
            base.AddObject("Tribunes", tribunes);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Billet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Billet : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Billet.
        /// </summary>
        /// <param name="int">Valeur initiale de la propriété int.</param>
        /// <param name="numSocio">Valeur initiale de la propriété numSocio.</param>
        /// <param name="idPlace">Valeur initiale de la propriété idPlace.</param>
        /// <param name="idMatch">Valeur initiale de la propriété idMatch.</param>
        public static Billet CreateBillet(global::System.Int32 @int, global::System.String numSocio, global::System.Int32 idPlace, global::System.Int32 idMatch)
        {
            Billet billet = new Billet();
            billet.@int = @int;
            billet.numSocio = numSocio;
            billet.idPlace = idPlace;
            billet.idMatch = idMatch;
            return billet;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 @int
        {
            get
            {
                return _int;
            }
            set
            {
                if (_int != value)
                {
                    OnintChanging(value);
                    ReportPropertyChanging("int");
                    _int = StructuralObject.SetValidValue(value, "int");
                    ReportPropertyChanged("int");
                    OnintChanged();
                }
            }
        }
        private global::System.Int32 _int;
        partial void OnintChanging(global::System.Int32 value);
        partial void OnintChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numSocio
        {
            get
            {
                return _numSocio;
            }
            set
            {
                OnnumSocioChanging(value);
                ReportPropertyChanging("numSocio");
                _numSocio = StructuralObject.SetValidValue(value, false, "numSocio");
                ReportPropertyChanged("numSocio");
                OnnumSocioChanged();
            }
        }
        private global::System.String _numSocio;
        partial void OnnumSocioChanging(global::System.String value);
        partial void OnnumSocioChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPlace
        {
            get
            {
                return _idPlace;
            }
            set
            {
                OnidPlaceChanging(value);
                ReportPropertyChanging("idPlace");
                _idPlace = StructuralObject.SetValidValue(value, "idPlace");
                ReportPropertyChanged("idPlace");
                OnidPlaceChanged();
            }
        }
        private global::System.Int32 _idPlace;
        partial void OnidPlaceChanging(global::System.Int32 value);
        partial void OnidPlaceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMatch
        {
            get
            {
                return _idMatch;
            }
            set
            {
                OnidMatchChanging(value);
                ReportPropertyChanging("idMatch");
                _idMatch = StructuralObject.SetValidValue(value, "idMatch");
                ReportPropertyChanged("idMatch");
                OnidMatchChanged();
            }
        }
        private global::System.Int32 _idMatch;
        partial void OnidMatchChanging(global::System.Int32 value);
        partial void OnidMatchChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Billet__idMatch__267ABA7A", "Match")]
        public Match Match
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Match>("Model.FK__Billet__idMatch__267ABA7A", "Match").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Match>("Model.FK__Billet__idMatch__267ABA7A", "Match").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Match> MatchReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Match>("Model.FK__Billet__idMatch__267ABA7A", "Match");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Match>("Model.FK__Billet__idMatch__267ABA7A", "Match", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Billet__idPlace__22AA2996", "Places")]
        public Places Places
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Places>("Model.FK__Billet__idPlace__22AA2996", "Places").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Places>("Model.FK__Billet__idPlace__22AA2996", "Places").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Places> PlacesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Places>("Model.FK__Billet__idPlace__22AA2996", "Places");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Places>("Model.FK__Billet__idPlace__22AA2996", "Places", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Billet__numSocio__1BFD2C07", "Socios")]
        public Socios Socios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Socios>("Model.FK__Billet__numSocio__1BFD2C07", "Socios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Socios>("Model.FK__Billet__numSocio__1BFD2C07", "Socios").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Socios> SociosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Socios>("Model.FK__Billet__numSocio__1BFD2C07", "Socios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Socios>("Model.FK__Billet__numSocio__1BFD2C07", "Socios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Match")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Match : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Match.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="intitule">Valeur initiale de la propriété intitule.</param>
        /// <param name="coefMatch">Valeur initiale de la propriété coefMatch.</param>
        /// <param name="dateMatch">Valeur initiale de la propriété dateMatch.</param>
        public static Match CreateMatch(global::System.Int32 id, global::System.String intitule, global::System.Double coefMatch, global::System.DateTime dateMatch)
        {
            Match match = new Match();
            match.id = id;
            match.intitule = intitule;
            match.coefMatch = coefMatch;
            match.dateMatch = dateMatch;
            return match;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String intitule
        {
            get
            {
                return _intitule;
            }
            set
            {
                OnintituleChanging(value);
                ReportPropertyChanging("intitule");
                _intitule = StructuralObject.SetValidValue(value, false, "intitule");
                ReportPropertyChanged("intitule");
                OnintituleChanged();
            }
        }
        private global::System.String _intitule;
        partial void OnintituleChanging(global::System.String value);
        partial void OnintituleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double coefMatch
        {
            get
            {
                return _coefMatch;
            }
            set
            {
                OncoefMatchChanging(value);
                ReportPropertyChanging("coefMatch");
                _coefMatch = StructuralObject.SetValidValue(value, "coefMatch");
                ReportPropertyChanged("coefMatch");
                OncoefMatchChanged();
            }
        }
        private global::System.Double _coefMatch;
        partial void OncoefMatchChanging(global::System.Double value);
        partial void OncoefMatchChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateMatch
        {
            get
            {
                return _dateMatch;
            }
            set
            {
                OndateMatchChanging(value);
                ReportPropertyChanging("dateMatch");
                _dateMatch = StructuralObject.SetValidValue(value, "dateMatch");
                ReportPropertyChanged("dateMatch");
                OndateMatchChanged();
            }
        }
        private global::System.DateTime _dateMatch;
        partial void OndateMatchChanging(global::System.DateTime value);
        partial void OndateMatchChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Billet__idMatch__267ABA7A", "Billet")]
        public EntityCollection<Billet> Billet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Billet>("Model.FK__Billet__idMatch__267ABA7A", "Billet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Billet>("Model.FK__Billet__idMatch__267ABA7A", "Billet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Places")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Places : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Places.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="idTribune">Valeur initiale de la propriété idTribune.</param>
        public static Places CreatePlaces(global::System.Int32 id, global::System.Int32 idTribune)
        {
            Places places = new Places();
            places.id = id;
            places.idTribune = idTribune;
            return places;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTribune
        {
            get
            {
                return _idTribune;
            }
            set
            {
                OnidTribuneChanging(value);
                ReportPropertyChanging("idTribune");
                _idTribune = StructuralObject.SetValidValue(value, "idTribune");
                ReportPropertyChanged("idTribune");
                OnidTribuneChanged();
            }
        }
        private global::System.Int32 _idTribune;
        partial void OnidTribuneChanging(global::System.Int32 value);
        partial void OnidTribuneChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Billet__idPlace__22AA2996", "Billet")]
        public EntityCollection<Billet> Billet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Billet>("Model.FK__Billet__idPlace__22AA2996", "Billet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Billet>("Model.FK__Billet__idPlace__22AA2996", "Billet", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Places__idTribun__21B6055D", "Tribunes")]
        public Tribunes Tribunes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunes>("Model.FK__Places__idTribun__21B6055D", "Tribunes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunes>("Model.FK__Places__idTribun__21B6055D", "Tribunes").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tribunes> TribunesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunes>("Model.FK__Places__idTribun__21B6055D", "Tribunes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tribunes>("Model.FK__Places__idTribun__21B6055D", "Tribunes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Socios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Socios : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Socios.
        /// </summary>
        /// <param name="numSocio">Valeur initiale de la propriété numSocio.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété prenom.</param>
        /// <param name="adresse">Valeur initiale de la propriété adresse.</param>
        /// <param name="codePostal">Valeur initiale de la propriété codePostal.</param>
        /// <param name="telephone">Valeur initiale de la propriété telephone.</param>
        /// <param name="mdp">Valeur initiale de la propriété mdp.</param>
        public static Socios CreateSocios(global::System.String numSocio, global::System.String nom, global::System.String prenom, global::System.String adresse, global::System.String codePostal, global::System.String telephone, global::System.String mdp)
        {
            Socios socios = new Socios();
            socios.numSocio = numSocio;
            socios.nom = nom;
            socios.prenom = prenom;
            socios.adresse = adresse;
            socios.codePostal = codePostal;
            socios.telephone = telephone;
            socios.mdp = mdp;
            return socios;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numSocio
        {
            get
            {
                return _numSocio;
            }
            set
            {
                if (_numSocio != value)
                {
                    OnnumSocioChanging(value);
                    ReportPropertyChanging("numSocio");
                    _numSocio = StructuralObject.SetValidValue(value, false, "numSocio");
                    ReportPropertyChanged("numSocio");
                    OnnumSocioChanged();
                }
            }
        }
        private global::System.String _numSocio;
        partial void OnnumSocioChanging(global::System.String value);
        partial void OnnumSocioChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false, "nom");
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, false, "prenom");
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, false, "adresse");
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codePostal
        {
            get
            {
                return _codePostal;
            }
            set
            {
                OncodePostalChanging(value);
                ReportPropertyChanging("codePostal");
                _codePostal = StructuralObject.SetValidValue(value, false, "codePostal");
                ReportPropertyChanged("codePostal");
                OncodePostalChanged();
            }
        }
        private global::System.String _codePostal;
        partial void OncodePostalChanging(global::System.String value);
        partial void OncodePostalChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String telephone
        {
            get
            {
                return _telephone;
            }
            set
            {
                OntelephoneChanging(value);
                ReportPropertyChanging("telephone");
                _telephone = StructuralObject.SetValidValue(value, false, "telephone");
                ReportPropertyChanged("telephone");
                OntelephoneChanged();
            }
        }
        private global::System.String _telephone;
        partial void OntelephoneChanging(global::System.String value);
        partial void OntelephoneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mdp
        {
            get
            {
                return _mdp;
            }
            set
            {
                OnmdpChanging(value);
                ReportPropertyChanging("mdp");
                _mdp = StructuralObject.SetValidValue(value, false, "mdp");
                ReportPropertyChanged("mdp");
                OnmdpChanged();
            }
        }
        private global::System.String _mdp;
        partial void OnmdpChanging(global::System.String value);
        partial void OnmdpChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Billet__numSocio__1BFD2C07", "Billet")]
        public EntityCollection<Billet> Billet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Billet>("Model.FK__Billet__numSocio__1BFD2C07", "Billet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Billet>("Model.FK__Billet__numSocio__1BFD2C07", "Billet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Table : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Table.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="idTribune">Valeur initiale de la propriété idTribune.</param>
        public static Table CreateTable(global::System.Int32 id, global::System.Int32 idTribune)
        {
            Table table = new Table();
            table.id = id;
            table.idTribune = idTribune;
            return table;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTribune
        {
            get
            {
                return _idTribune;
            }
            set
            {
                OnidTribuneChanging(value);
                ReportPropertyChanging("idTribune");
                _idTribune = StructuralObject.SetValidValue(value, "idTribune");
                ReportPropertyChanged("idTribune");
                OnidTribuneChanged();
            }
        }
        private global::System.Int32 _idTribune;
        partial void OnidTribuneChanging(global::System.Int32 value);
        partial void OnidTribuneChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Table__idTribune__1ED998B2", "Tribunes")]
        public Tribunes Tribunes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunes>("Model.FK__Table__idTribune__1ED998B2", "Tribunes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunes>("Model.FK__Table__idTribune__1ED998B2", "Tribunes").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tribunes> TribunesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunes>("Model.FK__Table__idTribune__1ED998B2", "Tribunes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tribunes>("Model.FK__Table__idTribune__1ED998B2", "Tribunes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Tribunes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tribunes : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Tribunes.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        /// <param name="capacite">Valeur initiale de la propriété capacite.</param>
        /// <param name="prix">Valeur initiale de la propriété prix.</param>
        public static Tribunes CreateTribunes(global::System.Int32 id, global::System.String nom, global::System.Int32 capacite, global::System.Double prix)
        {
            Tribunes tribunes = new Tribunes();
            tribunes.id = id;
            tribunes.nom = nom;
            tribunes.capacite = capacite;
            tribunes.prix = prix;
            return tribunes;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false, "nom");
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 capacite
        {
            get
            {
                return _capacite;
            }
            set
            {
                OncapaciteChanging(value);
                ReportPropertyChanging("capacite");
                _capacite = StructuralObject.SetValidValue(value, "capacite");
                ReportPropertyChanged("capacite");
                OncapaciteChanged();
            }
        }
        private global::System.Int32 _capacite;
        partial void OncapaciteChanging(global::System.Int32 value);
        partial void OncapaciteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double prix
        {
            get
            {
                return _prix;
            }
            set
            {
                OnprixChanging(value);
                ReportPropertyChanging("prix");
                _prix = StructuralObject.SetValidValue(value, "prix");
                ReportPropertyChanged("prix");
                OnprixChanged();
            }
        }
        private global::System.Double _prix;
        partial void OnprixChanging(global::System.Double value);
        partial void OnprixChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Places__idTribun__21B6055D", "Places")]
        public EntityCollection<Places> Places
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Places>("Model.FK__Places__idTribun__21B6055D", "Places");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Places>("Model.FK__Places__idTribun__21B6055D", "Places", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__Table__idTribune__1ED998B2", "Table")]
        public EntityCollection<Table> Table
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Table>("Model.FK__Table__idTribune__1ED998B2", "Table");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Table>("Model.FK__Table__idTribune__1ED998B2", "Table", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
