
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Administrador_de_entradas_para_la_Superliga.GlobalSvc
{

using System;
    using System.Collections.Generic;
    
public partial class Places
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Places()
    {

        this.Billet = new HashSet<Billet>();

    }


    public int id { get; set; }

    public int idTribune { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Billet> Billet { get; set; }

    public virtual Tribunes Tribunes { get; set; }

}

}
