
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Administrador_de_entradas_para_la_Superliga.GlobalSvc
{

using System;
    using System.Collections.Generic;
    
public partial class Socios
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Socios()
    {

        this.Billet = new HashSet<Billet>();

    }


    public string numSocio { get; set; }

    public string nom { get; set; }

    public string prenom { get; set; }

    public string adresse { get; set; }

    public string codePostal { get; set; }

    public string telephone { get; set; }

    public string mdp { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Billet> Billet { get; set; }

}

}
