
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Administrador_de_entradas_para_la_Superliga.GlobalSvc
{

using System;
    using System.Collections.Generic;
    
public partial class Table
{

    public int id { get; set; }

    public int idTribune { get; set; }



    public virtual Tribunes Tribunes { get; set; }

}

}
