USE [master]
GO

/****** Object:  Database [TP-VD]    Script Date: 17/04/2018 13:56:41 ******/
CREATE DATABASE [TP-VD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TP-VD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SOPIPING\MSSQL\DATA\TP-VD.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TP-VD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SOPIPING\MSSQL\DATA\TP-VD_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TP-VD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TP-VD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TP-VD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TP-VD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TP-VD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TP-VD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TP-VD] SET ARITHABORT OFF 
GO

ALTER DATABASE [TP-VD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TP-VD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TP-VD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TP-VD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TP-VD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TP-VD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TP-VD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TP-VD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TP-VD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TP-VD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TP-VD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TP-VD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TP-VD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TP-VD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TP-VD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TP-VD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TP-VD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TP-VD] SET RECOVERY FULL 
GO

ALTER DATABASE [TP-VD] SET  MULTI_USER 
GO

ALTER DATABASE [TP-VD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TP-VD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TP-VD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TP-VD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TP-VD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TP-VD] SET  READ_WRITE 
GO

